version: '3.9'

volumes:
  cry-data:

services:
  cry-db:
    container_name: "cry-database"
    image: mysql:8.0.29-oracle
    ports:
      - "3306:3306"
    volumes:
      - cry-data:/var/cry-app/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=cry
    networks:
      - cry-network

  server:
    container_name: "cry-server"
    build:
      context: ./../
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - cry-network
    depends_on:
      - cry-db

networks:
  cry-network:
    name: 'cry-network-default'