
name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: stop pm2
        run: pm2 stop crynfly-java || echo skipping....
      - name: delete current instance
        run: pm2 delete crynfly-java || echo skipping....
      - name: Check Out Repo 
        uses: actions/checkout@v2
      - name: Build
        run: gradle build
      - name: grant permissions
        run: chmod +x ./run.sh
      - name: run
        run: pm2 start sh run.sh --name "crynfly-java"
