
name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2
      - name: Build
        run: ./gradlew build


